[package]
name = "gateway-tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2", features = ["macros"] }
tauri-plugin-shell = "2"
tokio = { version = "1", features = ["full"] }
tokio-serial = "5"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
